nodeLinker: hoisted
ignoreScripts: true
autoInstallPeers: true
strictPeerDependencies: false
registries:
  default: https://registry.npmjs.org/

allowBuilds:
  esbuild: false
  msw: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - polpo-tailwind-config@0.1.1
  - polpo@0.1.23
